<?php

// Hour names for 24hour system
$this->hour_names_24 = array(
	'0','1','2','3','4','5',
	'6','7','8','9','10','11',
	'12','13','14','15','16','17',
	'18','19','20','21','22','23',
	'next 0','next 1','next 2','next 3','next 4','next 5',
	'next 6','next 7','next 8','next 9','next 10','next 11'
	) ;

// Hour names for 12hour system
$this->hour_names_12 = array(
	'AM 0','AM 1','AM 2','AM 3','AM 4','AM 5',
	'AM 6','AM 7','AM 8','AM 9','AM 10','AM 11',
	'PM 0','PM 1','PM 2','PM 3','PM 4','PM 5',
	'PM 6','PM 7','PM 8','PM 9','PM 10','PM 11',
	'next AM 0','next AM 1','next AM 2','next AM 3','next AM 4','next AM 5',
	'next AM 6','next AM 7','next AM 8','next AM 9','next AM 10','next AM 11'
	) ;

// Austrian holidays
/* $this->holidays = array(
	'2003-1-1'=>1,'2003-1-6'=>1,'2003-4-21'=>1,'2003-5-1'=>1,
	'2003-5-29'=>1,'2003-6-9'=>1,'2003-6-19'=>1, '2003-8-15'=>1,
	'2003-10-26'=>1,'2003-11-1'=>1,'2003-12-8'=>1,'2003-12-25'=>1,
	'2003-12-26'=>1,

	'2004-1-1'=>1,'2004-1-6'=>1,'2004-4-12'=>1,'2004-5-1'=>1,
	'2004-5-20'=>1,'2004-5-31'=>1,'2004-6-10'=>1,'2004-8-15'=>1,
	'2004-10-26'=>1,'2004-11-1'=>1,'2004-12-8'=>1,'2004-12-25'=>1,
	'2004-12-25'=>1,

	); */

// Can't use tags (for options)
$this->date_short_names = array(
	'0.','1.','2.','3.','4.','5.','6.','7.','8.','9.',
	'10.','11.','12.','13.','14.','15.','16.','17.','18.','19.',
	'20.','21.','22.','23.','24.','25.','26.','27.','28.','29.',
	'30.','31.'
	) ;

// Can use tags
$this->date_long_names = array(
	'0.','1.','2.','3.','4.','5.','6.','7.','8.','9.',
	'10.','11.','12.','13.','14.','15.','16.','17.','18.','19.',
	'20.','21.','22.','23.','24.','25.','26.','27.','28.','29.',
	'30.','31.'
	) ;

// Can't use tags (for options)
$this->week_numbers = array('Woche 0','Woche 1','Woche 2','Woche 3','Woche 4','Woche 5','Woche 6') ;

// Can't use tags (for options & minicalendar)
$this->week_short_names = array('So','Mo','Di','Mi','Do','Fr','Sa','So') ;

// Can use tags (for Monthly & Weekly View)
$this->week_middle_names = array('So','Mo','Di','Mi','Do','Fr','Sa','So') ;

// Can use tags (for Daily View)
$this->week_long_names = array('Sonntag','Montag','Dienstag','Mittwoch','Donnerstag','Freitag','Samstag','Sonntag') ;

// Can't use tags (for options)
$this->month_short_names = array('0','Jan','Feb','Mär','Apr','Mai','Jun','Jul','Aug','Sep','Okt','Nov','Dez') ; // Germany
//$this->month_short_names = array('0','Jän','Feb','Mär','Apr','Mai','Jun','Jul','Aug','Sep','Okt','Nov','Dez') ; // Austria

// Can use tags
$this->month_middle_names = array('0','Jan','Feb','Mär','Apr','Mai','Jun','Jul','Aug','Sep','Okt','Nov','Dez') ; // Germany
//$this->month_middle_names = array('0','Jän','Feb','Mär','Apr','Mai','Jun','Jul','Aug','Sep','Okt','Nov','Dez') ; // Austria

// Can use tags
$this->month_long_names = array('0','Januar','Februar','März','April','Mai','Juni','Juli','August','September','Oktober','November','Dezember') ; // Germany
//$this->month_long_names = array('0','Jänner','Februar','März','April','Mai','Juni','Juli','August','September','Oktober','November','Dezember') ; // Austria

// Don't change keys at all, but change values only
$this->byday2langday_w = array('SU'=>'So','MO'=>'Mo','TU'=>'Di','WE'=>'Mi','TH'=>'Do','FR'=>'Fr','SA'=>'Sa') ;

// Don't change keys at all, but change values only
$this->byday2langday_m = array(
	'1SU'=>'1. Sonntag','1MO'=>'1. Montag','1TU'=>'1. Dienstag','1WE'=>'1. Mittwoch','1TH'=>'1. Donnerstag','1FR'=>'1. Freitag','1SA'=>'1. Samstag',
	'2SU'=>'2. Sonntag','2MO'=>'2. Montag','2TU'=>'2. Dienstag','2WE'=>'2. Mittwoch','2TH'=>'2. Donnerstag','2FR'=>'2. Freitag','2SA'=>'2. Samstag',
	'3SU'=>'3. Sonntag','3MO'=>'3. Montag','3TU'=>'3. Dienstag','3WE'=>'3. Mittwoch','3TH'=>'3. Donnerstag','3FR'=>'3. Freitag','3SA'=>'3. Samstag',
	'4SU'=>'4. Sonntag','4MO'=>'4. Montag','4TU'=>'4. Dienstag','4WE'=>'4. Mittwoch','4TH'=>'4. Donnerstag','4FR'=>'4. Freitag','4SA'=>'4. Samstag',
	'-1SU'=>'Letzter Sonntag','-1MO'=>'Letzter Montag','-1TU'=>'Letzter Dienstag','-1WE'=>'Letzter Mittwoch','-1TH'=>'Letzter Donnerstag','-1FR'=>'Letzter Freitag','-1SA'=>'Letzter Samstag'
	) ;

?>
