<?php

$pico_configs_can_be_override = array(
	'wraps_auto_register' => 'bool' ,
	'auto_register_class' => 'class' ,
	'show_listasindex' => 'bool' ,
	'contents_order_in_cat' => 'text' ,
	'show_breadcrumbs' => 'bool' ,
	'show_pagenavi' => 'bool' ,
	'show_printicon' => 'bool' ,
	'show_tellafriend' => 'bool' ,
	'use_taf_module' => 'bool' ,
	'filters' => 'text' ,
	'filters_forced' => 'text' ,
	'filters_prohibited' => 'text' ,
	'use_vote' => 'bool' ,
	'guest_vote_interval' => 'int' ,
	'htmlheader' => 'text' ,
	'allow_each_htmlheader' => 'bool' ,
	'css_uri' => 'text' ,
	'images_dir' => 'text' ,
	'tpl_viewcontent' => 'template' ,
	'tpl_content_form' => 'template' ,
	'tpl_category_form' => 'template' ,
	'tpl_listcontents' => 'template' ,
	'extra_fields_class' => 'class' ,
	'extra_fields_cat_class' => 'class' ,
	'extra_images_dir' => 'text' ,
	'extra_images_size' => 'text' ,
	'comment_dirname' => 'text' ,
	'comment_forum_id' => 'int' ,
	'comment_order' => 'text' ,
	'comment_view' => 'text' ,
	'comment_posts_num' => 'int' ,
) ;

?>